### ISSUE TITLE
Good work and a fork of forks

### ISSUE THREAD

**Issue by magnusica** [rognerud/dbt2looker-bigquery#4]
Good work. 

Did fork your repo and i modified it a bit. Please have a look. https://github.com/rognerud/dbt2looker-bigquery/compare/main...magnusica:dbt2looker-bigquery:feature/some_improvements_likely

Maybe not everything is too your liking but it pretty much generates as looker generates the lookml.

**Comment by rognerud** [comment]
Thanks Magnus I think I will try to integrate it :)
Keeping the code as similar as the default code, is my intention as well 👍
